/**
 * Auto-generated migration map for trust-center
 * Maps old API function names to generated @autional/shared/generated/api
 * Generated by: python scripts/generate_api_ts.py --migration trust-center
 */

import * as Generated from '@autional/shared/generated/api';

export const getPenTestReports = Generated.compliancePublicPenetrationTestReports;
export const getAuditFindings = Generated.compliancePublicAuditFindings;
export const getBreachNotifications = Generated.compliancePublicBreachNotifications;
export const getAuditLogs = Generated.adminAuditLogs;
export const getNotificationTemplates = Generated.notificationsTemplates;
export const getSubprocessors = Generated.compliancePublicSubprocessors;
export const getAuditPublicStats = Generated.auditPublicStats;
export const getAuditPublicHashchain = Generated.auditPublicHashchain;
export const getAuditPublicLogsSummary = Generated.auditPublicLogsSummary;
export const getStorageEncryptionStatus = Generated.storagePublicEncryptionStatus;
export const getPublicReports = Generated.storagePublicReports;
export const getPublicCertifications = Generated.compliancePublicCertifications;
